---
title: "Covid-19 India Map"
output: html_document
 
---

```{r setup, include=FALSE}
#setup code chunk
knitr::opts_chunk$set(echo = TRUE)
```


```{r ,include=FALSE}
#---Before running following chunks set this project folder as working directory---#
#...with this command -> setwd(".../Covid19-map")...#

#packages for data manipulation

setwd("D:/Profession/jobs/feverr/30-10-2021-US/Covid19-map")
library(readr)
library(dplyr)
library(plyr)
library(sf)
```


```{r, include=FALSE}
#loading COVID-19 India data and filtering for 1st oct 2021

data_ex <- read_csv("states.csv")%>% 
  filter(Date=="2021-10-01")%>%
  filter(State!="India")%>%
  select(c("State","Confirmed"))%>%
  arrange(State)
State <- as.character(data_ex$State)
```


```{r, include=F,echo=F,message=FALSE,error=F,warning=F}
#loading shape file and merging with covid19 data

map_data <- read_sf("India_State_Shapefile/India_State_Shapefile/India_State_Boundary.shp")%>%
  arrange(Name)%>%
  cbind(State,.)%>%
  merge(.,data_ex,by="State")%>%
  st_as_sf()
```


```{r, echo=FALSE,include=F}
#loading packages to build map

library(tmap)
library(tmaptools)
pal=get_brewer_pal("-RdYlGn", n = 5,contrast = c(0.4,1))
```


```{r,echo=FALSE,include=F}
#building static map

map_static<-tm_shape(map_data) +
  tm_fill(col =  "Confirmed",style = "quantile", alpha=1, palette = pal)+
  tm_bubbles(size = "Confirmed",col="Confirmed",palette="Greys")+
  tm_text("State",remove.overlap=T, size=0.5)+
  tm_borders(col="grey",lwd=1, alpha = 1)+
  tm_layout(frame = F)+
  tm_compass(type = "4star",show.labels = 1,size=2, position = c("left", "bottom"))+
  tm_credits("Source: https://www.covid19india.org/",position = c("left", "bottom"))+
  tm_legend(legend.outside=T,legend.outside.position=c("right","bottom"),title="Total Confirmed Cases")

tmap_mode("plot")
```


## COVID-19 India Confirmed Cases As Of 1 Oct 2021
```{r, echo=FALSE,include=T,message=FALSE,error=F,warning=F}
#ploting the Static Map

map_static
```


```{r, echo=FALSE,include=F}
#building the interective map

map_interective<-tm_shape(map_data) +
  tm_fill(col =  "Confirmed",style = "quantile", alpha=1, palette = pal,popup.vars = c("State","Confirmed"))+
  tm_bubbles(size = "Confirmed",col = "Confirmed",interactive=T,popup.vars="Confirmed",palette="Greys",legend.size.show=F)+
  tm_text("State",size=0.5)+
  tm_borders(col="grey",lwd=1,alpha = 0.5)+
  tm_layout(frame = T, outer.margins = 0, inner.margins = 0,bg.color="lightblue")+
  tm_view(set.view = 4, alpha = 1, set.zoom.limits=c(3,8),view.legend.position=c("right","top") )+
  tm_legend(legend.outside=T,legend.outside.position=c("right","bottom"),title="Total Confirmed Cases")

tmap_mode("view")
```


## COVID-19 India Confirmed Cases As Of 1 Oct 2021
```{r, echo=FALSE,include=T}
#ploting the Interective COVID-19 India Map

map_interective
```
